name: Add article list
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: chmod 777 ./bin/create_list_data.sh
      - run: ./bin/create_list_data.sh
